version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest # Or a specific version like 2019-latest
    container_name: mssql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Galvan2483 # Replace with a strong password
      - MSSQL_PID=Developer # Or Express, Standard, Enterprise
    ports:
      - "1433:1433" # Maps host port 1434 to container port 1433
    volumes:
      - mssql-data:/var/opt/mssql # Persist data in a named volume
    restart: unless-stopped # Restart the container unless explicitly stopped
    networks:
      - default

  app:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: mp-backend
    environment:
      - PORT=3000
      - RATE_TIME_LIMIT=15
      - RATE_REQUEST_LIMIT=100
      - DB_HOST=mssql
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASSWORD=Galvan2483 # Ensure this matches the SA_PASSWORD above
      - DB_NAME=mp # Replace with your actual database name
      - JWT_SECRET=tu-super-secreto-en-produccion
      - JWT_EXPIRES_IN=7d
      - CORS_ORIGIN=*
      - NODE_ENV=production
    ports:
      - "3000:3000" # Maps host port 3000 to container port 3000
    depends_on:
      - mssql # Ensure the database starts before the app
    restart: unless-stopped # Restart the container unless explicitly stopped
    networks:
      - default

  frontend:
      build:
        context: ./frontend
        dockerfile: dockerfile
      container_name: mp-frontend
      environment:
        - REACT_APP_API_URL=http://localhost:3000
      ports:
        - "3001:80" # Maps host port 8080 to container port 80
      depends_on:
        - app # Ensure the backend starts before the frontend
      restart: unless-stopped # Restart the container unless explicitly stopped
      networks:
        - default

volumes:
  mssql-data: # Define the named volume for data persistence
networks:
  default:
    driver: bridge